import { defineCatalogEntry } from "./catalog/define-catalog-entry.js";

/**
 * One row per CMS catalog key. Optional `surface` / `usesSectionImage` only when
 * not the defaults (alt / false). Mirror changes in server `section.catalog.js`.
 */
export const SECTION_CATALOG_ENTRIES = [
  defineCatalogEntry({ key: "overview", name: "Overview", category: "content", tags: ["text", "image"], usesSectionImage: true }),
  defineCatalogEntry({ key: "text_media", name: "Text + Media", category: "content", tags: ["text", "image"] }),
  defineCatalogEntry({ key: "key_benefits", name: "Key Benefits", category: "features", tags: ["cards", "benefits"] }),
  defineCatalogEntry({ key: "team", name: "Team", category: "features", tags: ["cards", "people"] }),
  defineCatalogEntry({ key: "editorial_banner", name: "Editorial Banner", category: "hero", tags: ["hero", "full-bleed"], surface: "fixed", usesSectionImage: true }),
  defineCatalogEntry({ key: "feature_spotlight", name: "Feature Spotlight", category: "features", tags: ["cards", "spotlight"] }),
  defineCatalogEntry({ key: "process_steps", name: "Process Steps", category: "features", tags: ["steps", "process"] }),
  defineCatalogEntry({ key: "cta_band", name: "CTA Band", category: "cta", tags: ["cta", "band"], surface: "fixed" }),
  defineCatalogEntry({ key: "split_cta", name: "CTA — Gradient split", category: "cta", tags: ["cta", "gradient", "image"], surface: "fixed", usesSectionImage: true }),
  defineCatalogEntry({ key: "contact_us", name: "Contact Us", category: "content", tags: ["contact", "global"], contentScope: "global" }),
  defineCatalogEntry({ key: "contact_form", name: "Contact Form", category: "forms", tags: ["contact", "form", "enterprise"] }),
  defineCatalogEntry({ key: "newsletter_band", name: "Newsletter Band", category: "forms", tags: ["newsletter", "capture"] }),
  defineCatalogEntry({ key: "form_split", name: "Form — Split column", category: "forms", tags: ["form", "split", "lead"] }),
  defineCatalogEntry({ key: "statement_band", name: "Statement Band", category: "hero", tags: ["hero", "typography"], surface: "fixed", usesSectionImage: true }),
  defineCatalogEntry({ key: "bento_grid", name: "Bento Grid", category: "features", tags: ["bento", "mosaic"] }),
  defineCatalogEntry({ key: "horizon_gallery", name: "Horizon Gallery", category: "content", tags: ["gallery", "slider"], surface: "fixed" }),
  defineCatalogEntry({ key: "split_narrative", name: "Split Narrative", category: "content", tags: ["story", "sticky"], usesSectionImage: true }),
  defineCatalogEntry({ key: "pillar_destinations", name: "Pillar Destinations", category: "features", tags: ["pillars", "links"] }),
  defineCatalogEntry({ key: "orbit_hero", name: "Orbit Hero", category: "hero", tags: ["hero", "product-frame"], surface: "fixed", usesSectionImage: true }),
  defineCatalogEntry({ key: "card_stack", name: "Card Stack", category: "features", tags: ["stack", "scroll"] }),
  defineCatalogEntry({ key: "feature_tabs", name: "Tabs — Vertical", category: "tabs", tags: ["tabs", "vertical", "preview"] }),
  defineCatalogEntry({ key: "tabs_vertical", name: "Tabs — Vertical", category: "tabs", tags: ["tabs", "vertical"], renderKey: "feature_tabs" }),
  defineCatalogEntry({ key: "tabs_horizontal", name: "Tabs — Horizontal", category: "tabs", tags: ["tabs", "horizontal", "pills"] }),
  defineCatalogEntry({ key: "tabs_underline", name: "Tabs — Underline", category: "tabs", tags: ["tabs", "underline", "editorial"] }),
  defineCatalogEntry({ key: "tabs_success_stories", name: "Tabs — Success Stories", category: "tabs", tags: ["tabs", "horizontal", "icons", "case-study"] }),
  defineCatalogEntry({ key: "pricing_tiers", name: "Pricing Tiers", category: "pricing", tags: ["pricing", "plans"] }),
  defineCatalogEntry({ key: "masonry_quotes", name: "Masonry Quotes", category: "social_proof", tags: ["testimonials", "masonry"] }),
  defineCatalogEntry({ key: "metric_rail", name: "Metric Rail", category: "data", tags: ["metrics", "proof"] }),
  defineCatalogEntry({ key: "site_builder_hero", name: "Site Builder Hero", category: "hero", tags: ["builder", "hero"], surface: "fixed", usesSectionImage: true }),
  defineCatalogEntry({ key: "template_gallery", name: "Template Gallery", category: "content", tags: ["templates", "gallery"], surface: "fixed" }),
  defineCatalogEntry({ key: "builder_feature_cards", name: "Builder Feature Cards", category: "features", tags: ["features", "cards"] }),
  defineCatalogEntry({ key: "domain_search_band", name: "Domain Search Band", category: "content", tags: ["domain", "search"], surface: "fixed" }),
  defineCatalogEntry({ key: "website_build_steps", name: "Website Build Steps", category: "content", tags: ["steps", "guide"] }),
  defineCatalogEntry({ key: "video_banner", name: "Video Banner", category: "hero", tags: ["video", "full-bleed"], surface: "fixed" }),
  defineCatalogEntry({ key: "cast_profiles", name: "Cast Profiles", category: "features", tags: ["cast", "profiles", "people"] }),
  defineCatalogEntry({ key: "why_choose", name: "Why Choose", category: "features", tags: ["cards", "cta"] }),
  defineCatalogEntry({ key: "stats", name: "Stats Strip", category: "data", tags: ["metrics", "strip"] }),
  defineCatalogEntry({ key: "related_courses", name: "Related Courses", category: "catalog", tags: ["courses", "cards"] }),
  defineCatalogEntry({ key: "curriculum", name: "Curriculum", category: "catalog", tags: ["learning", "list"] }),
  defineCatalogEntry({ key: "partners", name: "Partners", category: "social_proof", tags: ["logos", "partners"], contentScope: "global" }),
  defineCatalogEntry({ key: "partners_marquee", name: "Partners — Logo Marquee", category: "social_proof", tags: ["logos", "marquee"], contentScope: "global" }),
  defineCatalogEntry({ key: "training_options", name: "Training Options", category: "features", tags: ["cards", "options"] }),
  defineCatalogEntry({ key: "awards", name: "Awards & Recognition", category: "social_proof", tags: ["awards", "cards"] }),
  defineCatalogEntry({ key: "in_page_nav", name: "In-Page Navigation", category: "navigation", tags: ["sticky", "links"], contentScope: "global", surface: "fixed" }),
  defineCatalogEntry({ key: "testimonials", name: "Testimonials", category: "social_proof", tags: ["quotes", "reviews"] }),
  defineCatalogEntry({ key: "customer_testimonials", name: "Customer Testimonials", category: "social_proof", tags: ["carousel", "reviews", "global"], contentScope: "global" }),
  defineCatalogEntry({
    key: "page_testimonials",
    name: "Page Testimonials",
    category: "social_proof",
    tags: ["carousel", "reviews", "page"],
    renderKey: "customer_testimonials",
    contentScope: "page",
  }),
  defineCatalogEntry({ key: "faq", name: "FAQ", category: "accordion", tags: ["accordion", "questions"] }),
  defineCatalogEntry({ key: "faq_two_column", name: "FAQ — Split column", category: "accordion", tags: ["accordion", "split", "title-side"] }),
  defineCatalogEntry({ key: "promo_modal", name: "Promo Modal", category: "overlays", tags: ["modal", "delay", "overlay"], surface: "fixed" }),
  defineCatalogEntry({ key: "comparison_table", name: "Comparison Table", category: "comparison", tags: ["table", "compare"] }),
  defineCatalogEntry({ key: "media_mosaic", name: "Media Mosaic", category: "media", tags: ["gallery", "mosaic", "images"] }),
  defineCatalogEntry({ key: "timeline_vertical", name: "Timeline — Vertical", category: "timeline", tags: ["timeline", "journey"] }),
  defineCatalogEntry({ key: "trust_badges", name: "Trust Badges", category: "trust", tags: ["trust", "badges", "compliance"] }),
  defineCatalogEntry({ key: "learning_path", name: "Learning Path", category: "learning", tags: ["learning", "path", "steps"] }),
  defineCatalogEntry({ key: "resources", name: "Resources", category: "catalog", tags: ["resources", "cards"] }),
  defineCatalogEntry({ key: "products", name: "Products Grid", category: "catalog", tags: ["products", "grid"] }),
  defineCatalogEntry({ key: "catalog", name: "Course Catalog", category: "catalog", tags: ["courses", "filters"] }),
  defineCatalogEntry({ key: "entity_directory", name: "Entity Directory", category: "catalog", tags: ["directory", "filters"] }),
  defineCatalogEntry({ key: "latest_blogs", name: "Latest Blogs", category: "content", tags: ["blogs", "articles", "latest"], contentScope: "global" }),
  defineCatalogEntry({ key: "blog_directory", name: "Blog Directory", category: "catalog", tags: ["blogs", "directory", "search"] }),
  defineCatalogEntry({
    key: "vendor_link_grid",
    name: "Vendor Link Grid",
    category: "content",
    tags: ["content", "links", "vendors", "grid"],
    contentScope: "global",
  }),
  defineCatalogEntry({
    key: "sarder_ecosystem",
    name: "Sarder Ecosystem",
    category: "content",
    tags: ["ecosystem", "logos", "spine", "partners"],
    surface: "fixed",
    usesSectionImage: true,
  }),
  defineCatalogEntry({ key: "hero_classic", name: "Hero — Classic", category: "hero", tags: ["hero", "cta"], usesSectionImage: true }),
  defineCatalogEntry({ key: "hero_split", name: "Hero — Split", category: "hero", tags: ["hero", "split"], usesSectionImage: true }),
  defineCatalogEntry({ key: "hero_centered", name: "Hero — Centered", category: "hero", tags: ["hero", "centered"] }),
  defineCatalogEntry({ key: "hero_minimal", name: "Hero — Minimal", category: "hero", tags: ["hero", "minimal"] }),
  defineCatalogEntry({ key: "hero_media", name: "Hero — Media Slider", category: "hero", tags: ["hero", "slider"], surface: "fixed" }),
  defineCatalogEntry({ key: "hero_stats", name: "Hero — Stats", category: "hero", tags: ["hero", "metrics"] }),
  defineCatalogEntry({ key: "hero_asymmetric", name: "Hero — Asymmetric", category: "hero", tags: ["hero", "asymmetric"] }),
  defineCatalogEntry({ key: "hero_dual_cta", name: "Hero — Dual CTA", category: "hero", tags: ["hero", "cta"], usesSectionImage: true }),
  defineCatalogEntry({
    key: "hero_gradient_slider",
    name: "Hero — Gradient Slider",
    category: "hero",
    tags: ["hero", "slider", "gradient"],
    surface: "fixed",
  }),
];
